### ISSUE TITLE
Default / Built-in ruleset behavior doesn't work as described

### ISSUE THREAD

**Issue by bradlet** [stoplightio/spectral-action#635]
When trying to specify a core/provided ruleset, we did so before by specifying spectral-ruleset: "spectral:oas3". This stopped working because the ruleset is not being found in the github workspace (Separate issue potentially). Supposedly spectral-ruleset is an optional parameter, and if you don't use it, a built-in ruleset should be used. But getDefaultRulesetFile only searches the CWD for a default ruleset. If none are found, it errors out -- as opposed to using a built-in / core ruleset.

## Context
Extra lint job, which pops up after job that contains the spectral action lint step, never ends:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/47132003/170308816-33f8eaba-8d9f-4099-acc2-f6237901df22.png">
This one's been going for like 3 days now.

## Current Behavior
Aside from the extra lint job that never ends, the lint step in our build job ends in error, but is considered a success

When not specifying any spectral-ruleset you see:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/47132003/170308621-5e8037ca-5512-4814-818a-77fdc9aa596a.png">

When specifying a spectral-ruleset, attempting to use some existing core ruleset, you see this (Note: tried 'spectral:oas' in this run, but in others tried 'spectral:oas3' and 'oas3' -- same result each time)
<img width="780" alt="image" src="https://user-images.githubusercontent.com/47132003/170310812-7e07a885-4f95-4fe9-b696-ceb127e23eb3.png">

## Expected Behavior
1) When specifying some predefined spectral ruleset such as "spectral:oas3" it works as it did before (we had been on v0.5.5 for at least a year) and the openApiV3 ruleset is used.
2) When the optional ruleset parameter isn't included, some built-in ruleset is used as described in the README.

## Possible Workaround/Solution
- Make getDefaultRulesetFile look for built-in rulesets if no ruleset is provided
- Make "spectral_ruleset" param values prefixed with 'spectral:' search stoplight-core (or stoplight-rulesets? However that works/used to work) for a matching ruleset with the suffixed tag.

## Steps to Reproduce
Setup and run a job that looks like this:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Spectral Lint
        uses: stoplightio/spectral-action@v0.5.5
        with:
          file_glob: ./public/api/*.yaml
          spectral_ruleset: "spectral:oas3"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
.
.
.
```
Or like this:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spectral Lint
        uses: stoplightio/spectral-action@v0.8.1
        with:
          file_glob: ./public/api/*.yaml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
.
.
.
```

## Environment
- Version used: v0.8.2
- Environment name and version (e.g. Chrome 39, node.js 5.4): ubuntu-latest
- Operating System and version (desktop or mobile): desktop
- Link to your environment/workspace/project: private project
